### ISSUE TITLE
Git Merge: 12/26/2019 - _scaffold Error

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#97] opened 2019-12-26 20:01 UTC
Just merged git repo with my float using script to test #70  and I got the following error while trying to launch Py4Web:

Traceback (most recent call last):
  File "D:\Dev\dashproj\dashproj\py4web\py4web\core.py", line 825, in import_app
    module_name, init
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps\_scaffold\__init__.py", line 7, in <module>
    from . models import db
  File "apps\_scaffold\models.py", line 5, in <module>
    from .common import db, Field
  File "apps\_scaffold\common.py", line 102, in <module>
    from celery import Celery
ModuleNotFoundError: No module named 'celery'

Py4Web still suceeds in running Bottle and hosting.

**Comment by MBfromOK** [comment] 2019-12-26 20:02
FWIW: I overwrote everything I had with changes from Master

**Comment by mdipierro** [comment] 2019-12-27 09:00
sorry. Try now.

**Comment by MBfromOK** [comment] 2019-12-29 05:56
Tried again, still unable to test as the dashboard won't load.

Most recent attempt nearly mirrors #99 returning error:

Traceback (most recent call last):
  File "D:\Dev\dashproj\dashproj\py4web\py4web\core.py", line 826, in import_app
    module_name, init
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps\_dashboard\__init__.py", line 24, in <module>
    error_storage = ErrorStorage()
  File "D:\Dev\dashproj\dashproj\py4web\py4web\core.py", line 701, in __init__
    Field("snapshot", "json")
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 592, in define_table
    table = self.lazy_define_table(tablename, *fields, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 627, in lazy_define_table
    polymodel=polymodel)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 798, in create_table
    return self.migrator.create_table(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\migrator.py", line 282, in create_table
    self.adapter.create_sequence_and_triggers(query, table)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 881, in create_sequence_and_triggers
    self.execute(query)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\__init__.py", line 67, in wrap
    return f(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 413, in execute
    rv = self.cursor.execute(command, *args[1:], **kwargs)
sqlite3.OperationalError: table "py4web_error" already exists

**Comment by mdipierro** [comment] 2019-12-29 09:40
Duplicate of issue #99

**Closed by mdipierro** 2019-12-29 09:40 UTC
