### ISSUE TITLE
Validator IS_IMAGE() does not work properly in a File Upload Form

### ISSUE THREAD

**Issue by ch-rigu** [web2py/py4web#329] opened 2020-11-03 18:42 UTC
Hi, it seems the validator IS_IMAGE does not work properly with a file upload form.
Ex:
This is my model
`db.define_table('wallpaper',
                Field('image', 'upload', required=True, requires=IS_IMAGE(extensions=('jpeg', 'png')))
                )`

controller:
`
form = Form(db.wallpaper)
if form.accepted:
    flash.set('Wallpaper saved', sanitize=True)
`

when I try to upload an image with extensions ".png" or ".jpeg" the file is uploaded and saved in the upload folders but the form gives the error "Invalid image" and no sql entry is created. If I remove the validator the image is uploaded and the sql entry is created. I'm not sure if this affect other validators.
I will try to fix it anyway :)

Cheers.
Chris.

**Comment by mdipierro** [comment] 2022-03-15 03:29
Cannot reproduce. Works for me with the code posted. Closing for now. Maybe reopen if not fixed

**Closed by mdipierro** 2022-03-15 03:29 UTC
Labels: form
