### ISSUE TITLE
TODO app: missing 'context' argument inserting items

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#699] opened 2022-03-14 17:56 UTC
The current TODO app always gives errors like the following when you try to insert a todo item:

```
[2022-03-14T18:51:42.779485]: Traceback (most recent call last):

  File "/home/nico/py4web/py4web/core.py", line 954, in wrapper

    ret = func(*func_args, **func_kwargs)

  File "/home/nico/py4web/py4web/core.py", line 923, in wrapper

    raise context["exception"]

  File "/home/nico/py4web/py4web/core.py", line 902, in wrapper

    context["output"] = func(*args, **kwargs)

  File "/home/nico/py4web/py4web/core.py", line 938, in wrapper

    if not requirement():

  File "/home/nico/py4web/py4web/core.py", line 996, in requirement

    session.on_request()

TypeError: on_request() missing 1 required positional argument: 'context'
```

**Comment by jpsteil** [comment] 2022-03-14 18:11
Looks to me like the problem is here:

def user_in(session):
    def requirement():
        session.on_request()
        return session.get("user", None) is not None

    return requirement

the session.on_request() call needs to pass the context parameter.
However, I'm not sure what should be passed.

Val?  Massimo?  Anyone?  Can you help?

-Jim

**Comment by jpsteil** [comment] 2022-03-14 18:14
@nico

This is a result of the big PR for the fixture change.

Also, I'm unclear on why the TODO app
uses @action.requires(user_in(session)) instead
of @action.uses('template.html', auth.user_id, db, session)

Is it because it is used in an API call environment instead of returning
html?

-Jim

**Comment by jpsteil** [comment] 2022-03-14 19:08
This is the first I'd seen it, didn't realize it was there.

-Jim

**Comment by mdipierro** [comment] 2022-03-14 19:31
I made a PR that addresses this but here some explanation and context.

In the TODO app there is no auth. There is a single user with id=1 not
stored in the database. This is to demonstrate how to use APIs.

The todo app is also old and uses

    @action.uses(session, db)
    @action.requires(user_in(session))

where action user_in_session) is simply a function that returns True/False.

Turns out action.requires is a bit of a nightmare because can duplicate of
the action.uses function but arguments are different, and they may depend
on each other. It was never documented and nobody uses it (I hope).

So I just made a new PR that will allow this:

    @action.uses(session, db, Requirement(user_in(session))

This clarifies that the condition user_in(session) requires a session.

1) does this make sense?
2) are you ok with deprecating action.requires()
3) I am not convinced the word "Requirement" here is a good choice. Should
we perhaps use "Filter" or "Condition"?

Massimo

**Comment by mdipierro** [comment] 2022-03-14 20:26
I like to read that in english as in

   @action.uses(Requirement(lambda: True))
   action uses requirement True

but the word requirement is overloaded because we use it to dependencies
between fixtures and not requirement is also a fixture. How about

   action uses condition True

?

**Comment by jpsteil** [comment] 2022-03-14 20:33
That works for me

-Jim

**Comment by mdipierro** [comment] 2022-03-15 01:47
Added documentation.

**Closed as completed** 2022-03-15 01:50 UTC
