### ISSUE TITLE
Py4web Docs: Causes browser freeze in Google Chrome

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#74] opened 2019-10-05 16:37 UTC
**My Google Chrome:** Version 77.0.3865.90 (Official Build)

I have been utilizing the pyDAL page of the docs heavily trying to build my code structure for database population.

I noticed that when I load the online (or locally hosted) docs (via browser link) that Chrome keeps freezing up every second or two for two to three seconds.  

I am thinking this could be caused by the js refreshing / reloading when it isn't required.  I have tried to troubleshoot, but am not familiar with the load process & syntax.  Maybe a modification to load & display the content onLoad and onClick would resolve this?

Alternatively, I noticed that the MM code syntax isn't working properly \<cough\>_**tables, tables with cite(s)**_\</cough\>, it is possible that the issue is being caused by the js trying to interpret the mm and not completing the load. -- In order to assist, I spent about 2 hours trying to fix the markmin code, can't seem to get cites embedded in tables to work or get tables to display correctly in either browser.

I am able to load this in Firefox without issue (or it handles it in a way to prevent this).

**Comment by MBfromOK** [comment] 2019-10-05 17:56
***NOTE:*** This is not unique to Py4web docs, web2py docs behave the same way.

**Comment by mdipierro** [comment] 2019-10-05 18:06
I suspect it is a slow regular expression processing. What is the page
exactly?

**Comment by MBfromOK** [comment] 2019-10-07 00:18
Noticed it with multiple pages, page I referenced the most: [Py4Web Docs: PyDAL](http://py4web.com/_documentation/static/index.html#chapter-05)

Interestingly enough, if that tab doesn't have focus (like now, when I am typing this reply) the browser is fine.

**Comment by mdipierro** [comment] 2019-10-11 05:36
Cannot reproduce. what OS? What chrome version?

**Comment by MBfromOK** [comment] 2019-11-23 23:58
Both
Windows 10 Pro 1903
> **My Google Chrome:** Version 77.0.3865.90 (Official Build)

and
Windows 10 Pro 1909
**Google Chrome:** Version 78.0.3904.108 (Official Build) (64-bit)

Windows 10 1909

**Comment by mdipierro** [comment] 2020-07-26 21:16
This is a windows specific issue. I do not have a windows machine to debug/reproduce. Can anybody help?

**Comment by nicozanf** [comment] 2020-08-31 21:53
Hi, it seems related to this problem https://groups.google.com/g/py4web/c/A2-5tz3FwyM/m/x59Z9pQpAQAJ .
Can you check if the problem is resolved by unchecking the 'preload pages for faster browsing and searching'Chrome setting on the Cookie section?

**Comment by mdipierro** [comment] 2020-12-06 18:54
we now use read the docs.

**Closed by mdipierro** 2020-12-06 18:54 UTC
